 import_coils_from_mgrid_input_format('make_plots', 1, 'coils_file_in', ...
     'coils.wista_15', 'save_mat_data', 1, 'output_mat_filename', ...
     'coilset_wista_15', 'winding_factors', [1], ...
     'coil_order', {'Mod'})
 
 